// <auto-generated />
namespace CornerkickWebMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vorname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vorname));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141610222_Vorname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
